Recipemanager2/员工管理/urls.py
from django.contrib import admin
from django.urls import path
from app01.views import admin, account, main, subpage1, lun, Ingre, home, category, favorite
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls import url

urlpatterns = [

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # Main page
    path('main/', main.home),
    path('main1/', main.home1),

    path('meun/main/add/', main.main_menu_add),
    path('meun/main/add1/', main.main_menu_add1),

    # home pages
    path('meun/<int:nid>/det/', home.meun_list),
    path('meun/<int:nid>/det1/', home.meun_list1),
    # path('meun/det1/', home.meun_list_cal),


    # Second menu

    path('meun/add/', main.add_meun),
    path('meun/<int:nid>/edit/', main.edit_meun),


    # my favorite

    path('meun/<int:nid>/list/', favorite.fav_meun),
    path('meun/<int:nid>/list2/', favorite.fav_cook),

    path('meun/list/', favorite.fav_list),
    path('meun/<int:nid>/delete/', favorite.fav_dele),


    # Subpage1
    path('subpage1/', subpage1.page),
    path('subpage2/', subpage1.page2),
    path('subpage3/', subpage1.page3),
    path('subpage4/', subpage1.page4),
    path('subpage5/', subpage1.page5),
    path('subpage6/', subpage1.page6),
    path('subpage7/', subpage1.page7),
    path('subpage8/', subpage1.page8),
    path('subpage9/', subpage1.page9),
    path('subpage10/', subpage1.page10),
    path('subpage11/', subpage1.page11),
    path('subpage12/', subpage1.page12),
    path('subpage13/', subpage1.page13),
    path('subpage14/', subpage1.page14),


    # Ingredient
    path('Ingredientm/', Ingre.meat),
    path('Ingredientm/add/', Ingre.madd),
    path('Ingredientv/', Ingre.veg),
    path('Ingredientv/add/', Ingre.vadd),
    path('Ingredienta/', Ingre.aux),
    path('Ingredienta/add/', Ingre.aadd),


    # Category
    path('category/list/', category.page),

    # lun bo figure
    path('det_lun1/', lun.page1),
    path('det_lun2/', lun.page2),
    path('det_lun3/', lun.page3),

    # 管理员管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # register
    path('register/', account.regist),

    # personal profile
    path('person/list', account.person)
    
    



]

Recipemanager2/app01/models.py
from django.db import models


# Create your models here.


class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="Username", max_length=32)
    password = models.CharField(verbose_name="Password", max_length=64)

    def __str__(self):
        return self.username


class Menu(models.Model):
    """ all meun """
    name = models.CharField(verbose_name="Name", max_length=32)
    time = models.IntegerField(verbose_name="time need to be done")

    tem = models.IntegerField(verbose_name="temperature")
    inter = models.CharField(verbose_name="materials needed", max_length=256)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/')


class meat(models.Model):
    """ The ingredients """
    meat = models.CharField(verbose_name="Meat", max_length=16, default="Beef")
    quantity = models.IntegerField(default=1, verbose_name="Amount")

    def __str__(self):
        return self.meat


class Auxiliary(models.Model):
    """ The ingredients """
    aux = models.CharField(verbose_name="aux", max_length=16, default="Salt")

    quantity = models.IntegerField(default=1, verbose_name="Amount")

    def __str__(self):
        return self.aux


class vegetable(models.Model):
    """ The ingredients """
    veg = models.CharField(verbose_name="vegetable", max_length=16, default="coriander")
    quantity = models.IntegerField(default=1, verbose_name="Amount")

    def __str__(self):
        return self.veg


class home(models.Model):
    """ The data in home page"""

    name = models.CharField(verbose_name="Name", max_length=64)
    temperature = models.IntegerField(verbose_name="Temperature", default=0)
    time = models.IntegerField(verbose_name="Time")
    utensils = models.CharField(verbose_name="Utensils", max_length=128)
    cate_food = (
        (1, "Most popular"),
        (2, "Best taste"),
        (3, "Vegetarianism"),
        (4, "Gorgeous"),
        (5, "Fast speed"),
        (6, "Breakfast"),
        (7, "Homely recipes"),
        (8, "Baking"),
        (9, "Children's food"),
        (10, "Baking"),
        (11, "Stape Food"),
        (12, "Dessert"),
        (13, "Snack"),
        (14, "Western Food"),
    )
    cate = models.SmallIntegerField(verbose_name="Category", choices=cate_food, default=1)
    description = models.TextField(verbose_name="Description", max_length=256, default="Delicious")
    meat = models.ForeignKey('meat', models.CASCADE)
    auxiliary = models.ForeignKey('Auxiliary', models.CASCADE)
    veg = models.ForeignKey('vegetable', models.CASCADE)
    quan = models.IntegerField(verbose_name="Amount", default=1)

    steps = models.TextField(verbose_name="Steps", max_length=500)
    Rate_stars = (
        (1, "One star"),
        (2, "Two stars"),
        (3, "Three stars"),
        (4, "Four stars"),
        (5, "Five stars"),
    )
    rate = models.IntegerField(verbose_name="Rate", choices=Rate_stars, default=3)
    calories = models.DecimalField(verbose_name="Calories", max_digits=6, decimal_places=2, default=300)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/', default='Menu/10.jpeg')


class favorite(models.Model):
    """ The data in home page """
    name = models.CharField(verbose_name="Name", max_length=64)
    temperature = models.IntegerField(verbose_name="Temperature", default=0)
    time = models.IntegerField(verbose_name="Time")
    utensils = models.CharField(verbose_name="Utensils", max_length=128)
    cate_food = (
        (1, "Most popular"),
        (2, "Best taste"),
        (3, "Vegetarianism"),
        (4, "Gorgeous"),
        (5, "Fast speed"),
        (6, "Breakfast"),
        (7, "Homely recipes"),
        (8, "Baking"),
        (9, "Children's food"),
        (10, "Baking"),
        (11, "Stape Food"),
        (12, "Dessert"),
        (13, "Snack"),
        (14, "Western Food"),
    )
    cate = models.SmallIntegerField(verbose_name="Category", choices=cate_food, default=1)
    description = models.TextField(verbose_name="Description", max_length=256, default="Delicious")
    meat = models.ForeignKey('meat', models.CASCADE)
    auxiliary = models.ForeignKey('Auxiliary', models.CASCADE)
    veg = models.ForeignKey('vegetable', models.CASCADE)
    quan = models.IntegerField(verbose_name="Amount", default=1)

    steps = models.TextField(verbose_name="Steps", max_length=500)
    Rate_stars = (
        (1, "One star"),
        (2, "Two stars"),
        (3, "Three stars"),
        (4, "Four stars"),
        (5, "Five stars"),
    )
    rate = models.IntegerField(verbose_name="Rate", choices=Rate_stars, default=3)
    calories = models.DecimalField(verbose_name="Calories", max_digits=6, decimal_places=2, default=300)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/', default='Menu/10.jpeg')


class cust_recipe(models.Model):
    """ The user create their own recipes """
    name = models.CharField(verbose_name="Name", max_length=64)
    temperature = models.IntegerField(verbose_name="Temperature", default=0)
    time = models.IntegerField(verbose_name="Time")
    utensils = models.CharField(verbose_name="Utensils", max_length=128)
    cate_food = (
        (1, "Most popular"),
        (2, "Best taste"),
        (3, "Vegetarianism"),
        (4, "Gorgeous"),
        (5, "Fast speed"),
        (6, "Breakfast"),
        (7, "Homely recipes"),
        (8, "Baking"),
        (9, "Children's food"),
        (10, "Baking"),
        (11, "Stape Food"),
        (12, "Dessert"),
        (13, "Snack"),
        (14, "Western Food"),
    )
    cate = models.SmallIntegerField(verbose_name="Category", choices=cate_food, default=1)
    description = models.TextField(verbose_name="Description", max_length=256, default="Delicious")
    meat = models.ForeignKey('meat', models.CASCADE)
    auxiliary = models.ForeignKey('Auxiliary', models.CASCADE)
    veg = models.ForeignKey('vegetable', models.CASCADE)
    quan = models.IntegerField(verbose_name="Amount", default=1)

    steps = models.TextField(verbose_name="Steps", max_length=500)
    Rate_stars = (
        (1, "One star"),
        (2, "Two stars"),
        (3, "Three stars"),
        (4, "Four stars"),
        (5, "Five stars"),
    )
    rate = models.IntegerField(verbose_name="Rate", choices=Rate_stars, default=3)
    calories = models.DecimalField(verbose_name="Calories", max_digits=6, decimal_places=2, default=300)
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Menu/', default='Menu/10.jpeg')

Recipemanager2/app01/views/Ingre.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

""" for meat """


class MainMenuModelForm(BootStrapModelForm):
    class Meta:
        model = models.meat
        fields = "__all__"


def meat(request):
    queryset = models.meat.objects.all()

    return render(request, 'Ingrem.html', {"queryset": queryset})


def madd(request):
    """ Add meat ingredient """
    title = "Create your new meat ingredient"
    if request.method == 'GET':
        form = MainMenuModelForm()

        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = MainMenuModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/Ingredientm/')
    return render(request, 'upload_form.html', {"form": form, "title": title})


""" for vegetable """


class MainMenuModelForm_veg(BootStrapModelForm):
    class Meta:
        model = models.vegetable
        fields = "__all__"


def veg(request):
    queryset = models.vegetable.objects.all()

    return render(request, 'Ingrev.html', {"queryset": queryset})


def vadd(request):
    """ Add meat ingredient """
    title = "Create your new meat ingredient"
    if request.method == 'GET':
        form = MainMenuModelForm_veg()

        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = MainMenuModelForm_veg(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/Ingredientv/')
    return render(request, 'upload_form.html', {"form": form, "title": title})


""" for Auxiliary"""


class MainMenuModelForm_aux(BootStrapModelForm):
    class Meta:
        model = models.Auxiliary
        fields = "__all__"


def aux(request):
    queryset = models.Auxiliary.objects.all()

    return render(request, 'Ingrea.html', {"queryset": queryset})


def aadd(request):
    """ Add meat ingredient """
    title = "Create your new meat ingredient"
    if request.method == 'GET':
        form = MainMenuModelForm_aux()

        return render(request, 'upload_form.html', {"form": form, "title": title})
    form = MainMenuModelForm_aux(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/Ingredienta/')
    return render(request, 'upload_form.html', {"form": form, "title": title})

Recipemanager2/app01/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from django import forms
from app01.models import Admin
from app01 import models
from app01.utils.bootstrap import BootStrapForm
from app01.utils.encrypt import md5
from app01.utils.code import check_code
from io import BytesIO
from app01.utils.bootstrap import BootStrapModelForm
from django.core.exceptions import ValidationError


class AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(render_value=True),
        required=True,
    )

    class Meta:
        model = models.Admin
        fields = ["username", "password", "confirm_password"]
        widgets = {
            "password": forms.PasswordInput(render_value=True),

        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

    def clean_confirm_password(self):
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd:
            raise ValidationError("The password is different")
        # 返回什么，此字段以后保存到数据库就是什么。
        return confirm


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )
    code = forms.CharField(
        label="Verification code",
        widget=forms.TextInput,
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def regist(request):
    title = "Register your account"
    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'regist.html', {"form": form, "title": title})
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data)
        form.save()
        return redirect("/login/")

    return render(request, 'regist.html', {"form": form, "title": title})


def login(request):
    """ Login """

    form = LoginForm(data=request.POST)
    if form.is_valid():

        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            form.add_error("code", "Verification code is wrong")
            return render(request, 'login.html', {"form": form})

        # admin_object = models.Admin.objects.filter(username=form.cleaned_data["username"], password=form.cleaned_data["password"]).first()
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "Username or password is wrong!")
            # form.add_error("username", "用户名或密码错误")
            return render(request, 'login.html', {"form": form})

        request.session["info"] = {"id": admin_object.id, "name": admin_object.username}
        # session 可以保存7天， 7天之内不需要登录。7 天之后 session失效，要重新登录。
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect('/main/')

    return render(request, 'login.html', {"form": form})


def image_code(request):
    """ Generate vertification code """
    # 调用含pillow函数的文件,生成图片
    img, code_string = check_code()

    # print(code_string)
    # 写入到自己的cookie中，以便后续中获取验证码在进行校验
    request.session['image_code'] = code_string
    # 给Session设置一个60秒超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    stream.getvalue()

    return HttpResponse(stream.getvalue())


def logout(request):
    """ Logout """
    request.session.clear()

    return redirect('/login/')


def person(request):
    return render(request, 'personal.html')

Recipemanager2/app01/views/category.py
from django.shortcuts import render
from app01 import models


def page(request):
    queryset = models.home.objects.all()
    return render(request, 'category.html', {"queryset": queryset})

Recipemanager2/app01/views/home.py
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

from django.shortcuts import render, redirect, HttpResponse
from app01 import models


class MenuModelForm(BootStrapModelForm):
    class Meta:
        model = models.home
        fields = "__all__"
        # exclude = ["id"]




def meun_list(request, nid):
    queryset = models.home.objects.filter(id=nid)
    tools = int(request.POST.get("tools"))
    print(tools)
    return render(request, 'sec_menu.html', {"queryset": queryset, "tools": tools})


def meun_list1(request, nid):
    queryset = models.cust_recipe.objects.filter(id=nid)
    tools = int(request.POST.get("toolss"))
    print(tools)
    return render(request, 'sec_menu1.html', {"queryset": queryset, "tools": tools})

Recipemanager2/app01/views/lun.py
from django.shortcuts import render


def page1(request):
    return render(request, 'det_lun1.html')


def page2(request):
    return render(request, 'det_lun2.html')


def page3(request):
    return render(request, 'det_lun3.html')

Recipemanager2/app01/templates/add_meun.html
{% extends 'layout.html' %}

{% block content %}
	<div class="container">
		<div class="panel panel-default">
			<div class="panel-heading">{{ title }}</div>
			<div class="panel-body">
				<form method="post" enctype="multipart/form-data" novalidate>
					{% csrf_token %}
					{% for field in form %}
						<div class="form-group">
							<label>{{ field.label }}</label>
							{{ field }}
							<span style="color: red;">{{ field.errors.0 }}</span>

						</div>
					{% endfor %}
					<button type="submit" class="btn btn-primary">提交</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

Recipemanager2/app01/templates/change.html
{% extends 'layout.html' %}

{% block content %}
	<div class="container">
		<div class="panel panel-default">
			<div class="panel-heading">{{ title }}</div>
			<div class="panel-body">
				<form method="post" novalidate>
					{% csrf_token %}
					{% for field in form %}
						<div class="form-group">
							<label>{{ field.label }}</label>
							{{ field }}
							<span style="color: red;">{{ field.errors.0 }}</span>
{#							[错误1， 错误2】#}
							{#						<input type="text" class="form-control" placeholder="姓名" name="name">#}
						</div>
					{% endfor %}
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

Recipemanager2/app01/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Recipe Robot</title>
	<link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">


	<style>
        .navbar {
            border-radius: 0;
        }

	</style>
	{% block css %}

	{% endblock %}

</head>
<body>

<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
			        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

		</div>


		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li style="margin-top: 6px; margin-left: 1px">
					<img alt="Brand" style="height: 40px;width: 40px; "
					     src="{% static 'img/img_1.png' %}">
				</li>
				<li><a href="/main">Home</a></li>
				<li><a href="/category/list/">Category</a></li>
				<li><a href="/meun/list/">Myfavorite</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
					   aria-expanded="false">Ingredient<span class="caret"></span></a>

					<ul class="dropdown-menu">
						<li><a href="/Ingredientm/">Category meat</a></li>
						<li><a href="/Ingredientv/">Category vegetable</a></li>
						<li><a href="/Ingredienta/">Category Auxiliary</a></li>

						<li role="separator" class="divider"></li>
					</ul>
				</li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
					   aria-expanded="false">{{ request.session.info.name }} <span class="caret"></span></a>

					<ul class="dropdown-menu">
						<li><a href="/person/list">Personal profile</a></li>
						<li><a href="/admin/list">Admin management</a></li>
						<li><a href="/register/">Register</a></li>
						<li><a href="/logout/">Logout</a></li>
						<li role="separator" class="divider"></li>
					</ul>
				</li>
			</ul>

			<form method="get">
				<div class="input-group" style="float: right; width: 200px; padding: 9px">

					<input type="text" name="q" class="form-control" placeholder="Name or Calories..." value="">
					<span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
	                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
				</div>
			</form>

		</div>
	</div>
</div>





<div>
	{% block content %}{% endblock %}
</div>


<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}

</body>
</html>

Recipemanager2/app01/templates/main1.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
        .thumbnail {
            width: 100%;
            padding: 2px;
            margin-bottom: 20px;
            background-color: #e8e8e8;
            border: 18px solid honeydew;
            height: 530px;
        }

        .sub-header a {
            float: left;
            width: 100px;
            text-align: center;
            text-decoration: none;
            font-size: 14px;
        }

        .container .w {
            background-color: #fff;
        }

        .w {
            width: 1170px;
            height: 400px;
            margin-left: -15px;
        }


        .sub-header a img {
            width: 60px;
            height: 60px;

            margin: 0 auto 5px;
            border-radius: 50%;
        }


        .sub-header {
            margin-top: 20px;
            margin-left: 80px;
            width: 1170px;

        }

        .row {
            position: relative;
            padding-top: 15px;
            margin-left: 5px;
        }

        .item img {
            display: block;
            max-width: 100%;
            height: auto;
        }

        .carousel-inner {
            height: 200px;
            width: 1170px;
        }

        .four4 a {
            float: right;
        }

        .item1 img {
            width: 400px;
            height: 200px;
        }


        .caption {
            height: 150px;
        }

        .avatar {
            color: #fff;
            background-color: #adb5bd;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            font-size: 1rem;
            border-radius: 50%;
            height: 35px;
            width: 35px;
            float: right;
        }

        .bg-red {
            background-color: #f03 !important;
        }

        .sub-header1 {
            width: 1170px;
            height: 50px;
        }

        .sub-header3 a {
            width: 124px;
            margin-left: 15px;
        }

        .sub-header3 {
            margin-left: 75px;
            margin-top: 70px;
        }

        .bs-example {
            width: 1170px;
            margin-left: 0;

        }

        .sider {
            min-height: calc(100vh - 60px);
            background: #ffffff;
            font-family: "Roboto", sans-serif;
            font-weight: 400;
            padding: 0;
            width: 257px;


            border-right: 2px solid #e3e3e3;
            border-bottom: 2px solid #e3e3e3;
        }

        .nav-item {
            border-bottom: 2px solid #e3e3e3;
            margin-top: 50px;
        }

        .text-white {
            color: #fff !important;
        }


	</style>





	<div class="sider" style="float: left">
		<ul class="nav">
			<li class="nav-item" style="margin-top: 1px">
				<a style="background-color:#000; " href="/main/"
				   class="list-group-item list-group-item-warning"><h3 class="text-white">Home</h3></a>
			</li>
			<li class="nav-item">
				<a style="background-color: #ff5916 !important; " href="/main1/" class="list-group-item list-group-item-warning">
					<h3 class="text-white">My own recipes</h3></a>
			</li>
			<li class="nav-item">
				<a style="background-color: #44c553 !important; " href="/meun/main/add/"
				   class="list-group-item list-group-item-success"><h3 class="text-white">Create recipe</h3></a>
			</li>
			<li class="nav-item">
				<a style="background-color: #7832e2 !important; " href="/meun/main/add1/"
				   class="list-group-item list-group-item-info"><h3 class="text-white">Customize recipe</h3></a>
			</li>
			<li class="nav-item">
				<a style="background-color: #35bdff !important; " href="/meun/main/add/"
				   class="list-group-item list-group-item-danger"><h3 class="text-white">Share recipes</h3></a>
			</li>

			<li class="nav-item active">
				<a style="background-color: #ffde03 !important;" href="/meun/main/add/"
				   class="list-group-item list-group-item-primary"><h3 class="text-white">***</h3></a>
			</li>

		</ul>
	</div>

	<div class="container" style="margin-right: 0; margin-top: -20px; background-color: #f3f3f3">
		<h1></h1>
		<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title"><h3>My own recipes</h3></h3>
				</div>

		</div>



		<div class="bs-example" data-example-id="thumbnails-with-custom-content">
			<div class="row">
				<div class="row1">
					{% for obj in queryset %}
						<div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<img style="width: 290px ;height:290px" src="/media/{{ obj.img }}"
								     data-src="holder.js/100%x200" alt="100%x200">
								<div class="caption" id="formAdd">

									<h2>{{ obj.name }}</h2>
									<h5>Category: {{ obj.get_cate_display }}</h5>
									<h5>Description: {{ obj.description }}</h5>
									<h5>Comment: {{ obj.get_rate_display }}</h5>
									<h5>Calories: {{ obj.calories }} kal</h5>


									<div style="float: right; margin-top: -50px">
										<form action="/meun/{{ obj.id }}/det1/" method="POST">
											{% csrf_token %}
											<p>Quantity: <input type="text" name="toolss"
											                    style="width: 40px; border: 2px solid greenyellow"
											                    value="{{ obj.quan }}"></p>

											<input style="width: 100px" class="btn btn-success" role="button"
											       type="submit" value="Start!!!"/>
										</form>

									</div>


								</div>

							</div>
						</div>
					{% endfor %}

				</div>
			</div>
			<ul class="pagination">
				{{ page_string }}
			</ul>
		</div>
	</div>

{% endblock %}
{% block js %}
	<script>
        $(function () {
            bindBtnSaveEvent();

        })

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                alert("Save Successfully in my favorite");


            });
        }


	</script>



{% endblock %}

Recipemanager2/app01/templates/subpage1.html
{% extends 'layout.html' %}

{% block content %}
	{% load static %}
	<style>
        .panel-body {
            padding: 5px;
        }

        .panel-body img {
            width: 160px;
            height: 160px;
        }

        .text {
            float: right;
            padding-right: 500px;
        }
	</style>
	<div class="container">
		{% for obj in queryset %}
			<h1 style="color: #985f0d">{{ obj.get_cate_display}}</h1>
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title"><h3>{{ obj.name }}</h3></h3>
				</div>
				<div class="panel-body">
					<img src="/media/{{ obj.img }}">
					<div class="text">
						<h3>Description：{{ obj.description }}</h3>
						<h3>Score：{{ obj.get_rate_display }}</h3>
					</div>

				</div>
			</div>
		{% endfor %}

	</div>



{% endblock %}

Recipemanager2/app01/templates/upload_list.html
{% extends 'layout.html' %}

{% block content %}

	<div class="container">
		<form method="post" enctype="multipart/form-data">
			<input type="text" name="username">
			<input type="file" name="avatar">
			<input type="submit" name="提交">
		</form>
	</div>

{% endblock %}